### ISSUE TITLE
Problem: cannot build on windows11 X msys2

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#163]
build fails with this error
```
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  failed to run custom build command for `cxx-build v1.0.67 
  ...
  When building `cxx` from a git clone, git's symlink support needs
  to be enabled on platforms that have it off by default (Windows).
  Either use:

     $ git config --global core.symlinks true

  prior to cloning, or else use:

     $ git clone -c core.symlinks=true https://github.com/dtolnay/cxx

  for the clone.

```

**Comment by leejw51crypto** [comment]
i enabled symlink,still not working
windows_build.bat also not working

**Comment by leejw51crypto** [comment]
change to cxx-build = "1.0.72"
compiles fine

git symlink flag seems not working in latest windows 11 box

**Comment by elecming** [comment]
How about https://github.com/cronos-labs/play-cpp-sdk/blob/main/README.md?plain=1#L112

**Comment by leejw51crypto** [comment]
removed `.cargo/git` in home folder, no more "symlinks" error

for windows, symlinks are not enabled by default.
 [cxx.rs](http://cxx.rs/)  build fails with message symlinks not enabled
* turn on developer mode
* install git with symlinks support
* remove /c/Users/yourid/.cargo/git   <- very important
