### ISSUE TITLE
Problem: mac release minos is 11.0

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#168]
lower minos to 10.15

**Comment by elecming** [comment]
https://github.com/cronos-labs/play-cpp-sdk/blob/main/.github/workflows/mac-build.yml#L24 checkmac.sh is run in ci.

**Comment by elecming** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/92778185/182070587-1df00022-540b-4727-8905-6cedd6e4bae2.png">

**Comment by leejw51crypto** [comment]
yes, it seems, MACOSX_DEPLOYMENT_TARGET is not working correctly.
trying to change os to 10.15
