### ISSUE TITLE
Problem: Missing chain_id for wallet connect session

### ISSUE THREAD

**Issue by elecming** [cronos-labs/play-cpp-sdk#257]
Chain id could be Number or Null according to spec when create a session.

**Comment by damoncro** [comment]
![Screenshot_2022-10-31-14-52-31-886_com.defi.wallet.jpg](https://user-images.githubusercontent.com/92778185/198957501-4a04f043-8892-4bb4-9085-3548ffa22bf1.jpg)

See the tested default Preferred Chain is Cronos Mainnet.
