### ISSUE TITLE
Problem: missing wallet connect example of sending amount

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#30]
add send amount example with wallet  connect
in example folder

user can run 
```
cargo run --example basic
```

**Comment by tomtau** [comment]
it should be similar to the current example, just instead of `sign` one can call those transaction-related APIs https://github.com/crypto-com/game-sdk-extras/blob/main/wallet-connect/examples/web3.rs#L25

**Comment by tomtau** [comment]
@leejw51crypto for reference:
```rust
// eth_sendRawTransaction
middleware.send_raw_transaction(tx_bytes);
// eth_sendTransaction
middleware.send_transaction(tx, maybe_block)
// eth_signTransaction
middleware.sign_transaction(tx, from)
```

**Comment by tomtau** [comment]
you can use one of those methods

**Comment by leejw51crypto** [comment]
started

**Comment by tomtau** [comment]
https://github.com/cronos-labs/play-cpp-sdk/pull/77
