### ISSUE TITLE
adding a callback when connected or disconnected

### ISSUE THREAD

**Issue by bg6621** [cronos-labs/play-cpp-sdk#344]
adding a callback when connected or disconnected
user, can try again

callback will be called via channel, (unbounded mpsc channel)

_Originally posted by @leejw51crypto in https://github.com/cronos-labs/play-cpp-sdk/issues/3#issuecomment-1081630404_

**Comment by elecming** [comment]
Thanks for reporting. 

The callback is already implemented by [setup_callback_blocking](https://github.com/cronos-labs/play-cpp-sdk/blob/main/extra-cpp-bindings/src/lib.rs#L350). Examples are here: https://github.com/cronos-labs/play-cpp-sdk/blob/main/demo/examples/src/wallet_connect.cc#L75-L85.

Those events are sufficient for users to bind their personal implementations callbacks on C++. 

I guess it is not necessary to refactor it using channel. 
@leejw51crypto
