### ISSUE TITLE
Problem: not possible to pass back the WalletConnect connection string for display

### ISSUE THREAD

**Issue by tomtau** [cronos-labs/play-cpp-sdk#4]

**Comment by leejw51crypto** [comment]
connection string will be delivered via callback (mpsc channel)
1. displayed as qrcode
2. user activate the wallet and sign by qrcode
3. tx is signed, and can be used in broadcasting

**Comment by tomtau** [comment]
fixed in https://github.com/crypto-com/game-sdk-extras/pull/34
