### ISSUE TITLE
Problem: missing c++ example of Crypto.com Pay apis

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#61]
add c++ example for crypto.com pay api

**Comment by tomtau** [comment]
@leejw51crypto @damoncro one important thing to put in the example would be some sample server-side module which listens for the Webhooks: https://pay-docs.crypto.com/#api-reference-webhooks

> Normally Crypto.com Pay side expect merchants to check our payment status / listen to our webhook events on SERVER SIDE to confirm the payment is captured before delivering the goods. If only client side does the check then a hacker could forge a fake order to claim the goods in game
