### ISSUE TITLE
Problem: when trying to use sign legacy eth tx

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#64]
when using ethers,
` async fn sign_transaction`
 
doesn't work with this error below
```
sign_typed_transaction error Attempted to sign a transaction with no available signer. Hint: did you mean to use a SignerMiddleware
```

**Comment by tomtau** [comment]
@leejw51crypto can you post the code you use to construct a tx?

**Comment by tomtau** [comment]
oh, https://github.com/gakonst/ethers-rs/blob/b15d0f86438b31cb97f3acedecb9c6530d3d974c/ethers-providers/src/provider.rs#L640

**Comment by tomtau** [comment]
it should be overridden

**Comment by leejw51crypto** [comment]
ok i see
so need to add to the provider
