### ISSUE TITLE
Problem: CryptoComPaymentResponse is not full set

### ISSUE THREAD

**Issue by elecming** [cronos-labs/play-cpp-sdk#71]
The CryptoComPaymentResponse is currently a sub-set of CryptoPayObject, it is better to use full set, preferably all can be accessed in cpp.

**Comment by tomtau** [comment]
@damoncro actually no -- the subset is mostly all that is needed... the `CryptoComPaymentResponse` contains some undocumented fields that are not guaranteed to guaranteed to be in the API response... perhaps better is to deserialise just what is needed, maybe relax `CryptoComPaymentResponse`  a bit
