### ISSUE TITLE
Problem: missing packaging script 

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#88]
add command for generating full package including defi-wallet-core

for windows, cargo build should be done under visual studio x86_64 command shell

for mac, it's x86_64 compatible, and minos 10.15

- including header, c++ sources
- libraries for mac x86-64, windows 64bit

**Comment by elecming** [comment]
How about defi-wallet-core packages can be generated in defi-wallet-core-rs itself by release. play-cpp-sdk can use nix or just some github actions to download the release from defi-wallet-core-rs to do further packing?

**Comment by elecming** [comment]
This can relieve the play-cpp-sdk burden.

**Comment by leejw51crypto** [comment]
> How about defi-wallet-core packages can be generated in defi-wallet-core-rs itself by release. play-cpp-sdk can use nix or just some github actions to download the release from defi-wallet-core-rs to do further packing?

ok, that would work
